#!zsh
SCRIPT_DIR=$(dirname $(realpath $0))
LOCAL_DIR=$(realpath $SCRIPT_DIR/../)
NIXOS_DIR=/etc/nixos

# Move all files except for scripts/* and .gitignore
setopt extendedglob
files=(${LOCAL_DIR}/^(scripts|\.gitignore))
unsetopt extendedglob

for file in $files; do
  echo "Copying $file to $NIXOS_DIR"
  sudo cp -r $file $NIXOS_DIR
done

sudo nixos-rebuild switch --show-trace --flake /etc/nixos#default
cp $NIXOS_DIR/flake.lock $LOCAL_DIR
